name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/trellis-money-aws-postgresql
            git pull origin main
            pnpm install
            source ~/load-env.sh
            NODE_OPTIONS="--max-old-space-size=1536" pnpm run build
            source ~/load-env.sh && pm2 restart nextjs-app --update-env